apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    app: myapp   #  this is the label we will use as a selector in the service below.
spec:
  containers:
    - name: nginx 
      image: nginx


---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: myapp  ## here we use the label app of the Pod
  ports:
    - name: http
      port: 80 
      nodePort: 30020
  type: NodePort  # we are using the type=ClusterIP so that this service will only be accesible inside the kubernetes cluster (webapp container can access but outside the cluster can't)


